### ISSUE TITLE
Suggestion to Add Azure Permissions necessary to upload the Certificate 

### ISSUE THREAD

**Issue by kimigunn** [MicrosoftDocs/dynamics-365-project-operations#1]
[In order to compete setup in the Add an Azure Subscription to LCS Project - step #6 Upload the Certificate to Azure Management Certificate I had to be sure the user I was logged into as an Administrator or Co-Administrator.  It would be valuable to just have that mentioned somewhere in the article so a novice user that doesn't understand Azure can figure it out.  

It is easily done by selecting Add --> Co-Administrator from the Azure Subscription Access Control (IAM)
]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cdc0447c-b010-64c9-070c-aa208f9fafe1
* Version Independent ID: f65bf115-16f2-be87-5fd5-6542bfd6c0bd
* Content: [Add an Azure subscription to an LCS project](https://docs.microsoft.com/en-us/dynamics365/project-operations/environment/resource-add-azure-subscription-lcs-project)
* Content Source: [articles/environment/resource-add-azure-subscription-lcs-project.md](https://github.com/MicrosoftDocs/dynamics-365-project-operations-pr/blob/live/articles/environment/resource-add-azure-subscription-lcs-project.md)
* Service: **project-operations**
* GitHub Login: @sigitac
* Microsoft Alias: **sigitac**

**Comment by kfend** [comment]
@kimigunn - thank you for the feedback.
@sigitac - could you please take a look at this and update the topic as necessary?

**Comment by sigitac** [comment]
Noted, @kimigunn will add to the article
