### ISSUE TITLE
Need to edit this page for the Schedule Mode setting which has been added to Project Operations.

### ISSUE THREAD

**Issue by veeyeskay** [MicrosoftDocs/dynamics-365-project-operations#10]
Need to edit this page for the Schedule Mode setting which has been added to Project Operations. This is currently missing and we need to ensure to add the documentation for Schedule Mode in Project Operations.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd1e582a-2f17-6df0-f686-fea369a0ad9b
* Version Independent ID: abfee2a7-1914-e442-93a9-5dc6931ceef6
* Content: [What's new May 2021 - Project Operations lite deployment](https://docs.microsoft.com/en-us/dynamics365/project-operations/pro/whats-new/whats-new-may-2021-lite)
* Content Source: [articles/pro/whats-new/whats-new-may-2021-lite.md](https://github.com/MicrosoftDocs/dynamics-365-project-operations-pr/blob/live/articles/pro/whats-new/whats-new-may-2021-lite.md)
* Service: **dynamics-365-project-operations**
* Product: ****
* GitHub Login: @sigitac
* Microsoft Alias: **sigitac**

**Comment by sigitac** [comment]
Scheduling mode is available in the article, Features included in this release section. Please let us know if there are issues with displaying it on the browser window.
