### ISSUE TITLE
deleting project member is processed asynchronously.

### ISSUE THREAD

**Issue by TakiyaNakano-MSFT** [MicrosoftDocs/dynamics-365-project-operations#105]
[Enter feedback here]
Deleting a project team member is done asynchronously and takes several minutes from the time the delete operation is performed until the deletion is complete.
see the discussion in IcM 403438859

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9502f48e-90cb-bee1-c312-d545e61e9d94
* Version Independent ID: 17d7eb54-a1c4-f42f-c402-deb4b947959d
* Content: [Project team members](https://learn.microsoft.com/en-us/dynamics365/project-operations/project-management/project-team-members-overview)
* Content Source: [articles/project-management/project-team-members-overview.md](https://github.com/MicrosoftDocs/dynamics-365-project-operations/blob/main/articles/project-management/project-team-members-overview.md)
* Service: **dynamics-365-project-operations**
* GitHub Login: @ruhercul
* Microsoft Alias: **ruhercul**

**Comment by johnmichalak** [comment]
Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.
