### ISSUE TITLE
Changing legal entity using New Expense Mobile app

### ISSUE THREAD

**Issue by graymark3** [MicrosoftDocs/dynamics-365-project-operations#108]
Other than changing the D365 users's default company, is there any functionality for a user to change the company he is using in the new expense management mobile app? This tends to affect users that approve expense reports for employees in different legal entities.

Is there any workaround?

**Comment by mukumarm** [comment]
Hi 

As of now we have considered the default company assigned to the user to log the expenses. We are working on the same which allows the user to change the company. Approval feature is coming as part of GA along with profile change.

Regards
Mukesh Mutreja

**Comment by graymark3** [comment]
Hi Mukesh Mutreja

Thank you for update. The functionality you mention as part of GA such as approvals and changing legal entities, is there any timeline for this release?

As an end user, I would like to express our thanks for the new functionality in the Expense management module.

Kind Regards

Mark Gray

> 
> On ,Fri Aug 11 2023 20:30:31 GMT+1000 (Australian Eastern Standard Time),
