### ISSUE TITLE
Link for Mobile Experiences Team Channel just opens Teams.  Not channel seems to exist.

### ISSUE THREAD

**Issue by markschurmann** [MicrosoftDocs/dynamics-365-project-operations#111]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7f0c5ea1-938e-0e53-7f79-4c5d7baff6b3
* Version Independent ID: 7f0c5ea1-938e-0e53-7f79-4c5d7baff6b3
* Content: [Expense mobile app FAQ](https://learn.microsoft.com/en-us/dynamics365/project-operations/expense/new-expense-mobile-app-faq)
* Content Source: [articles/expense/new-expense-mobile-app-faq.md](https://github.com/MicrosoftDocs/dynamics-365-project-operations/blob/main/articles/expense/new-expense-mobile-app-faq.md)
* Service: **dynamics-365-project-operations**
* GitHub Login: @ramagadu
* Microsoft Alias: **ramagadu**

**Comment by johnmichalak** [comment]
@markschurmann Hello, yes, the link opens teams so you can join the Team's channel/group discussion. After you open Teams you are presented with a dialog box where you can join the Project Operations Discussions.

**Comment by markschurmann** [comment]
Sorry.  All the link does is open Teams.  There is no dialog presented.

Mark Schurmann
P 770-945-2330 ext 186, c 404-883-0166

**Comment by johnmichalak** [comment]
You should see this:

![image](https://github.com/MicrosoftDocs/dynamics-365-project-operations/assets/102557226/be48e1fc-0fdc-4ec2-9ac5-39dddf43875f)

If not, I would suggest contacting support to troubleshoot why it is not opening in Teams for you.

Here is the link if you would like to try to manually add it in your browser: https://teams.microsoft.com/l/channel/19%3A7f1fd50904c24fe9ab31b221a73fcc64%40thread.tacv2/Mobile%2520Experiences?groupId=b781f78d-32f2-432f-b1fa-265d8259f9be&tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47

**Comment by johnmichalak** [comment]
https://teams.microsoft.com/l/channel/19%3a8a60b9a0136a4879aeb618021cdcdc91%40thread.tacv2/General?groupId=b781f78d-32f2-432f-b1fa-265d8259f9be&tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47

**Comment by markschurmann** [comment]
Hi John,

When we attempt this using the Teams Web app rather than the Windows App, we get the following.  Shouldn’t the link include the code to grant access?

[A screenshot of a computer  Description automatically generated]



Mark Schurmann
P 770-945-2330 ext 186, c 404-883-0166

**Comment by johnmichalak** [comment]
I'm sorry you are having so much trouble with this. I was able to successfully sign up for it. It took a few minutes before the request was granted, but it worked. Let me check with the author to see if they have the invite code for the group.

**Comment by johnmichalak** [comment]
Hi Mark, if you send me you email address, I am told they can generate an invite for you to join the team. Hopefully that will get you into the group.

**Comment by markschurmann** [comment]
***@***.******@***.***>

Thanks

Mark Schurmann
P 770-945-2330 ext 186, c 404-883-0166

**Comment by johnmichalak** [comment]
If it fails again, email me directly. my username on here at microsoft.com.
