### ISSUE TITLE
False error

### ISSUE THREAD

**Issue by Kflanagan54** [MicrosoftDocs/dynamics-365-project-operations#112]
[Enter feedback here]
What about a time out issue where it states the user does not have a Project license but  they have a trial one. 
Allow pop up does not seem to fix it

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f9b5cae0-20ce-25f9-12a1-ad1d504142e9
* Version Independent ID: 558c0557-98cc-2070-c83c-759a50b9c533
* Content: [Troubleshoot working in the Task grid](https://learn.microsoft.com/en-us/dynamics365/project-operations/project-management/projectplanninguifaq)
* Content Source: [articles/project-management/projectplanningUIFAQ.md](https://github.com/MicrosoftDocs/dynamics-365-project-operations/blob/main/articles/project-management/projectplanningUIFAQ.md)
* Service: **dynamics-365-project-operations**
* GitHub Login: @ruhercul
* Microsoft Alias: **ruhercul**

**Comment by johnmichalak** [comment]
Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.
