### ISSUE TITLE
Be more specific than mentioning Common in Tenant

### ISSUE THREAD

**Issue by compashi** [MicrosoftDocs/dynamics-365-project-operations#122]
[Enter feedback here]
Can the documentation be more specific instead of mentioning Common in Tenant

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ebd04d90-7059-e1a1-3e0d-58695c210e2d
* Version Independent ID: ebd04d90-7059-e1a1-3e0d-58695c210e2d
* Content: [Install and configure the Expense mobile app](https://learn.microsoft.com/en-us/dynamics365/project-operations/expense/new-expense-mobile-app-install-and-configure)
* Content Source: [articles/expense/new-expense-mobile-app-install-and-configure.md](https://github.com/MicrosoftDocs/dynamics-365-project-operations/blob/main/articles/expense/new-expense-mobile-app-install-and-configure.md)
* Service: **dynamics-365-project-operations**
* GitHub Login: @mukumarm
* Microsoft Alias: **mukumarm**

**Comment by johnmichalak** [comment]
@compashi I am happy to reach out to the author to see if revisions can be made. Do you have a specific concern you are trying to address?
