### ISSUE TITLE
Fix "Mapping" typo in JSON body

### ISSUE THREAD

**Issue by NickMoores** [MicrosoftDocs/dynamics-365-project-operations#126]
In the table for "msdyn_CopyProjectV4" it lists one of the parameters as "TeamMembersMappint" but I think this is a typo and it should be: "TeamMembersMapping".

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4cdc2125-bf2a-985a-d44f-6449a469636a
* Version Independent ID: 5cdec51a-7530-a40f-cc70-6d3e7a838f76
* Content: [Develop project templates with Copy Project](https://learn.microsoft.com/en-us/dynamics365/project-operations/project-management/dev-copy-project)
* Content Source: [articles/project-management/dev-copy-project.md](https://github.com/MicrosoftDocs/dynamics-365-project-operations/blob/main/articles/project-management/dev-copy-project.md)
* Service: **dynamics-365-project-operations**
* GitHub Login: @abriccetti
* Microsoft Alias: **abriccetti**

**Comment by johnmichalak** [comment]
@NickMoores Thank you for letting us know. This has been fixed and the changes should go live later today.
