### ISSUE TITLE
Doc misses entities permissions for dual write app user security role

### ISSUE THREAD

**Issue by dwiederhso** [MicrosoftDocs/dynamics-365-project-operations#14]
Instructions say you need to give security role app user permissions:

- Currency Exchange Rate Type
- Chart Of Accounts
- Fiscal Calendar
- Ledger

you also need to have:

- Company
- Currency Exchange Rate
- Currency Exchange Rate Pair
- Currency Exchange Rate Type

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51dfaa6b-0294-a3c9-d134-ad6811b34540
* Version Independent ID: e22ab93a-6a24-510c-685e-b0d6d905c2ab
* Content: [Provision a new environment](https://docs.microsoft.com/en-gb/dynamics365/project-operations/environment/resource-provision-new-environment#update-security-settings-on-project-operations-on-dataverse)
* Content Source: [articles/environment/resource-provision-new-environment.md](https://github.com/MicrosoftDocs/dynamics-365-project-operations-pr/blob/live/articles/environment/resource-provision-new-environment.md)
* Service: **dynamics-365-project-operations**
* Product: ****
* GitHub Login: @sigitac
* Microsoft Alias: **sigitac**

**Comment by kfend** [comment]
@dwiederhso - thank you for the feedback. 
@sigitac - can you please take a look and address this as needed?

**Comment by sigitac** [comment]
Updated with two missing ones:
Company
Currency Exchange Rate Type

**Comment by kfend** [comment]
I have published the updated topic.
