### ISSUE TITLE
Broken link for work hours

### ISSUE THREAD

**Issue by sureshb87** [MicrosoftDocs/dynamics-365-project-operations#17]
Link referred for setting up work hours in this page is broken and getting 404 error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 601d791e-1056-8fc5-7245-f5eb800b462f
* Version Independent ID: 90c29920-2535-1bf3-3523-0d980af80770
* Content: [Define project calendars](https://docs.microsoft.com/en-us/dynamics365/project-operations/project-management/define-project-calendars)
* Content Source: [articles/project-management/define-project-calendars.md](https://github.com/MicrosoftDocs/dynamics-365-project-operations-pr/blob/live/articles/project-management/define-project-calendars.md)
* Service: **dynamics-365-project-operations**
* Product: ****
* GitHub Login: @ruhercul
* Microsoft Alias: **ruhercul**

**Comment by kfend** [comment]
@sureshb87 - thanks for pointing this out. The link has been fixed.
