### ISSUE TITLE
Project Service Automation Deprecation Date

### ISSUE THREAD

**Issue by kchanmon** [MicrosoftDocs/dynamics-365-project-operations#18]
Hello,

I am trying to find any information about the deadline to transfer from PSA to Project Operations. I can't seem to find any information from the documentations area from Microsoft. There have been rumors about this date being in October 2024, but this information is coming from Microsoft Partners and not Microsoft. I would like to ask for this to be part of the documentation if possible. Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e1e6e079-1d90-3d44-f3c5-6ff9580ca050
* Version Independent ID: 21c697b3-9d4c-f858-f3eb-74d017e87807
* Content: [What is Dynamics 365 Project Service Automation?](https://docs.microsoft.com/en-us/dynamics365/project-operations/psa/overview)
* Content Source: [articles/psa/overview.md](https://github.com/MicrosoftDocs/dynamics-365-project-operations-pr/blob/live/articles/psa/overview.md)
* Service: **dynamics-365-project-operations**
* GitHub Login: @stsporen
* Microsoft Alias: **ruhercul**

**Comment by kfend** [comment]
@kchanmon - thanks for the question/feedback. 
@ruhercul and @stsporen - can you take a look and address this?

**Comment by stsporen** [comment]
We provided guidance through the blog post:
https://cloudblogs.microsoft.com/dynamics365/bdm/2019/05/22/the-future-of-dynamics-365-for-project-service-automation-psa/

PSA is not longer available for purchase. The deadline is customer specific as when their current contract expires they will need to decide to move to Project Operations. Hence there is no date.

**Comment by kchanmon** [comment]
Thank you for the replies and explanation. I appreciate it! Have a great weekend.
