### ISSUE TITLE
psa to POpp

### ISSUE THREAD

**Issue by makdaddy8888** [MicrosoftDocs/dynamics-365-project-operations#19]
what happens to existing psa. Will they get automaticlly updated to POpp's?
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 526ce90c-54aa-73be-101d-d47aa02e58d3
* Version Independent ID: fa1d2d0c-f37a-cbac-56b1-e63c173b17b6
* Content: [Upgrade home page](https://docs.microsoft.com/en-us/dynamics365/project-operations/psa/upgrade-psa-home-page)
* Content Source: [articles/psa/upgrade-psa-home-page.md](https://github.com/MicrosoftDocs/dynamics-365-project-operations-pr/blob/live/articles/psa/upgrade-psa-home-page.md)
* Service: **dynamics-365-project-operations**
* Product: ****
* GitHub Login: @rumant
* Microsoft Alias: **rumant**

**Comment by ruhercul** [comment]
When upgrading from Project Service Automation (PSA) to Project Operations, customers can expect to see Project Operations listed as the app installed inside Power Platform Admin Center, PSA will no longer be displayed.
