### ISSUE TITLE
Insufficient information for feature | Update required

### ISSUE THREAD

**Issue by DeependraTomar** [MicrosoftDocs/dynamics-365-project-operations#2]
Below mentioned feature for Redesigned Expense Report does not mention that there is dependency for this feature to work on cases where there are already expense/receipts available in system which are not part of any expense report. In other case customer doesn't see any option to add existing expenses and deem it as a bug with application. Please update document to clearly explain the dependency also.

![image](https://user-images.githubusercontent.com/78141904/106115064-5846c400-6176-11eb-9142-78856b10f0b9.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87ab4bb1-c528-b73b-60e3-5f8a7828e7a1
* Version Independent ID: 18bf851a-dab8-6d9e-5641-121201df1186
* Content: [Redesigned expense reports](https://docs.microsoft.com/en-us/dynamics365/project-operations/prod-exp/ExpenseWorkspaceNew)
* Content Source: [articles/prod-exp/ExpenseWorkspaceNew.md](https://github.com/MicrosoftDocs/dynamics-365-project-operations-pr/blob/live/articles/prod-exp/ExpenseWorkspaceNew.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @ryansandness
* Microsoft Alias: **suvaidya**

**Comment by kfend** [comment]
@DeependraTomar - thank you for the feedback.
@suvaidya - please take a look and update the topic.

**Comment by suvaidya** [comment]
@DeependraTomar Thanks , this has been addressed.
