### ISSUE TITLE
Test Feedback

### ISSUE THREAD

**Issue by bishalgoswami** [MicrosoftDocs/dynamics-365-project-operations#20]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09792f2b-9dd9-0a0d-8aa1-382d7015fe33
* Version Independent ID: 6b0da156-2840-2114-7b35-567e5baa1eaf
* Content: [Sales process overview](https://docs.microsoft.com/en-us/dynamics365/project-operations/sales/sales-overview)
* Content Source: [articles/sales/sales-overview.md](https://github.com/MicrosoftDocs/dynamics-365-project-operations-pr/blob/live/articles/sales/sales-overview.md)
* Service: **dynamics-365-project-operations**
* GitHub Login: @rumant
* Microsoft Alias: **rumant**

**Comment by johnmichalak** [comment]
Closing because this is not an issue.
