### ISSUE TITLE
Establishing Dual Write Instructions out of Date

### ISSUE THREAD

**Issue by kimigunn** [MicrosoftDocs/dynamics-365-project-operations#21]
Documentation for establishing Dual Write seems out of date (https://docs.microsoft.com/en-us/dynamics365/project-operations/environment/resource-provision-new-environment#establish-a-dual-write-connection).

There is no longer the Link to CDS under the Manage Environment, there is the Power Platform Integration group where the option to Setup Dual-write application button is available.  

Screenshot included from a recently provisioned environment.

![ProjOps_SetupDual-WriteApplication_Nov2021](https://user-images.githubusercontent.com/72810573/139882680-411f5b8d-1686-46dc-94a2-85ac728ef181.jpg)
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51dfaa6b-0294-a3c9-d134-ad6811b34540
* Version Independent ID: e22ab93a-6a24-510c-685e-b0d6d905c2ab
* Content: [Provision a new environment](https://docs.microsoft.com/en-us/dynamics365/project-operations/environment/resource-provision-new-environment)
* Content Source: [articles/environment/resource-provision-new-environment.md](https://github.com/MicrosoftDocs/dynamics-365-project-operations-pr/blob/live/articles/environment/resource-provision-new-environment.md)
* Service: **dynamics-365-project-operations**
* Product: ****
* GitHub Login: @sigitac
* Microsoft Alias: **sigitac**

**Comment by kfend** [comment]
@kimigunn - Thank you for the feedback.
@sigitac - Can you please take a look at this? Thanks!
