### ISSUE TITLE
Duplication of bullet points within Update Security settings on Project Operations on Dataverse, Step #4 

### ISSUE THREAD

**Issue by kimigunn** [MicrosoftDocs/dynamics-365-project-operations#22]
In the Update security settings on Project Operations on Dataverse, Step #4 - the bullet list of items repeats "Currency Exchange Rate Type".  So the question is:  1) Is it just a duplicate; OR 2) should there be a validation for Currency Exchange Rate and/or Currency Exchange Rate Pair?

![image](https://user-images.githubusercontent.com/72810573/140239905-a667f758-6edb-4ebd-9948-4115b493a038.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51dfaa6b-0294-a3c9-d134-ad6811b34540
* Version Independent ID: e22ab93a-6a24-510c-685e-b0d6d905c2ab
* Content: [Provision a new environment](https://docs.microsoft.com/en-us/dynamics365/project-operations/environment/resource-provision-new-environment#establish-a-dual-write-connection)
* Content Source: [articles/environment/resource-provision-new-environment.md](https://github.com/MicrosoftDocs/dynamics-365-project-operations-pr/blob/live/articles/environment/resource-provision-new-environment.md)
* Service: **dynamics-365-project-operations**
* Product: ****
* GitHub Login: @sigitac
* Microsoft Alias: **sigitac**

**Comment by kfend** [comment]
This is fixed.
