### ISSUE TITLE
Installation of the demo data is not working

### ISSUE THREAD

**Issue by RobertRybaric** [MicrosoftDocs/dynamics-365-project-operations#24]
I replicated the installation steps on my own physical PC, as well as on 2 virtual machines, to be completely sure, that the issue is NOT caused by the infrastructure. Every time the same issue, please see the screenshot. Not possible to log-in, of course with CORRECT credentials.

![image](https://user-images.githubusercontent.com/35074341/141443752-13c4580e-2395-4b92-9952-8531246ea94c.png)

Here the error log:

Source	: Microsoft.IdentityModel.Clients.ActiveDirectory
Method	: CreateFromUnauthorizedResponseCommon
Date	: 11/12/2021
Time	: 10:22:06 AM
Error	: Unauthorized Http Status Code (401) was expected in the response
Parameter name: response
Stack Trace	: at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationParameters.CreateFromUnauthorizedResponseCommon(IHttpWebResponse response)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationParameters.CreateFromUnauthorizedResponse(HttpWebResponse response)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.GetAuthorityFromTargetService(Uri targetServiceUrl)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.ExecuteAuthenticateServiceProcess(Uri serviceUrl, ClientCredentials clientCredentials, X509Certificate2 userCert, UserIdentifier user, String clientId, Uri redirectUri, PromptBehavior promptBehavior, String tokenCachePath, Boolean isOnPrem, String authority, Uri& targetServiceUrl, AuthenticationContext& authContext, String& resource, CrmLogEntry logSink)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.DiscoverOrganizations(Uri discoveryServiceUri, ClientCredentials clientCredentials, X509Certificate2 loginCertificate, UserIdentifier user, String clientId, Uri redirectUri, PromptBehavior promptBehavior, String tokenCachePath, Boolean isOnPrem, String authority, CrmLogEntry logSink)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.DiscoverOrganizations(Uri discoveryServiceUri, ClientCredentials clientCredentials, UserIdentifier user, String clientId, Uri redirectUri, PromptBehavior promptBehavior, String tokenCachePath, Boolean isOnPrem, String authority, CrmLogEntry logSink)
   at Microsoft.Xrm.Tooling.CrmConnectControl.CrmConnectionManager.QueryOAuthDiscoveryServer(Uri discoServer, ClientCredentials liveCreds, UserIdentifier user, String clientId, Uri redirectUri, PromptBehavior promptBehavior, String tokenCachePath)
   at Microsoft.Xrm.Tooling.CrmConnectControl.CrmConnectionManager.FindCrmOnlineDiscoveryServer(ClientCredentials liveCreds)
   at Microsoft.Xrm.Tooling.CrmConnectControl.CrmConnectionManager.ValidateServerConnection(CrmOrgByServer selectedOrg)
======================================================================================================================

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16a875e9-428c-ad05-fc4f-6c3875e8c540
* Version Independent ID: bd55b01f-3b7e-83ab-c788-e46b513cd5e3
* Content: [Sample data installation](https://docs.microsoft.com/en-us/dynamics365/project-operations/psa/install-sample-data-3-x)
* Content Source: [articles/psa/install-sample-data-3-x.md](https://github.com/MicrosoftDocs/dynamics-365-project-operations-pr/blob/live/articles/psa/install-sample-data-3-x.md)
* Service: **dynamics-365-project-operations**
* GitHub Login: @ruhercul
* Microsoft Alias: **ruhercul**

**Comment by malkhawaja** [comment]
I have the same issue...

**Comment by ruhercul** [comment]
@malkhawaja  and @RobertRybaric  can you both confirm you are trying to install this demo data on PSA 3.x?   If so, please log support cases for our team to investigate.


> I replicated the installation steps on my own physical PC, as well as on 2 virtual machines, to be completely sure, that the issue is NOT caused by the infrastructure. Every time the same issue, please see the screenshot. Not possible to log-in, of course with CORRECT credentials.
> 
> ![image](https://user-images.githubusercontent.com/35074341/141443752-13c4580e-2395-4b92-9952-8531246ea94c.png)
> 
> Here the error log:
> 
> # Source : Microsoft.IdentityModel.Clients.ActiveDirectory
> Method : CreateFromUnauthorizedResponseCommon
> Date : 11/12/2021
> Time : 10:22:06 AM
> Error : Unauthorized Http Status Code (401) was expected in the response
> Parameter name: response
> Stack Trace : at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationParameters.CreateFromUnauthorizedResponseCommon(IHttpWebResponse response)
> at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationParameters.CreateFromUnauthorizedResponse(HttpWebResponse response)
> at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.GetAuthorityFromTargetService(Uri targetServiceUrl)
> at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.ExecuteAuthenticateServiceProcess(Uri serviceUrl, ClientCredentials clientCredentials, X509Certificate2 userCert, UserIdentifier user, String clientId, Uri redirectUri, PromptBehavior promptBehavior, String tokenCachePath, Boolean isOnPrem, String authority, Uri& targetServiceUrl, AuthenticationContext& authContext, String& resource, CrmLogEntry logSink)
> at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.DiscoverOrganizations(Uri discoveryServiceUri, ClientCredentials clientCredentials, X509Certificate2 loginCertificate, UserIdentifier user, String clientId, Uri redirectUri, PromptBehavior promptBehavior, String tokenCachePath, Boolean isOnPrem, String authority, CrmLogEntry logSink)
> at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.DiscoverOrganizations(Uri discoveryServiceUri, ClientCredentials clientCredentials, UserIdentifier user, String clientId, Uri redirectUri, PromptBehavior promptBehavior, String tokenCachePath, Boolean isOnPrem, String authority, CrmLogEntry logSink)
> at Microsoft.Xrm.Tooling.CrmConnectControl.CrmConnectionManager.QueryOAuthDiscoveryServer(Uri discoServer, ClientCredentials liveCreds, UserIdentifier user, String clientId, Uri redirectUri, PromptBehavior promptBehavior, String tokenCachePath)
> at Microsoft.Xrm.Tooling.CrmConnectControl.CrmConnectionManager.FindCrmOnlineDiscoveryServer(ClientCredentials liveCreds)
> at Microsoft.Xrm.Tooling.CrmConnectControl.CrmConnectionManager.ValidateServerConnection(CrmOrgByServer selectedOrg)
> #### Document Details
> ⚠ _Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking._
> 
> * ID: 16a875e9-428c-ad05-fc4f-6c3875e8c540
> * Version Independent ID: bd55b01f-3b7e-83ab-c788-e46b513cd5e3
> * Content: [Sample data installation](https://docs.microsoft.com/en-us/dynamics365/project-operations/psa/install-sample-data-3-x)
> * Content Source: [articles/psa/install-sample-data-3-x.md](https://github.com/MicrosoftDocs/dynamics-365-project-operations-pr/blob/live/articles/psa/install-sample-data-3-x.md)
> * Service: **dynamics-365-project-operations**
> * GitHub Login: @ruhercul
> * Microsoft Alias: **ruhercul**

**Comment by malkhawaja** [comment]
Hi @ruhercul , it appears that the package deployer files are old and I think they are outdated… so what I did is I took the data files then created a new package (new build) in visual studio , and used it in the new Package Deployer, and it worked.. but it took around 12 hrs to finish the upload!!! so it is recommended to leave it over night and make sure your device doesn’t turn off during that.
If you need I can provide you with the new package that I used, just let me know.

**Comment by ruhercul** [comment]
@malkhawaja  thanks for the feedback.  Please log a support case.

Kind Regards.
