### ISSUE TITLE
Correction needed - No instruction about N:1 relationship between Time Entry and Bookable Resource

### ISSUE THREAD

**Issue by kesun1** [MicrosoftDocs/dynamics-365-project-operations#25]
Hi,
Please kindly check the session "Set up Dimension value defaulting using the mappings features of the platform". The N:1 relationship between Time entry and Bookable resource that mentioned in the section is not described before. I understand the concept but it may cause confusion to others. Thanks.

Best regards,
Keisuke

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16b8484b-5318-cc90-73a1-9ad706433079
* Version Independent ID: 838a88d6-d73e-e063-9041-344410c13f26
* Content: [Add required custom fields to price setup and transactional entities](https://docs.microsoft.com/en-us/dynamics365/project-operations/pricing-costing/add-custom-fields-price-setup-transactional-entities#add-custom-fields-to-forms-views-and-business-rules)
* Content Source: [articles/pricing-costing/add-custom-fields-price-setup-transactional-entities.md](https://github.com/MicrosoftDocs/dynamics-365-project-operations-pr/blob/live/articles/pricing-costing/add-custom-fields-price-setup-transactional-entities.md)
* Service: **dynamics-365-project-operations**
* Product: ****
* GitHub Login: @rumant
* Microsoft Alias: **suvaidya**

**Comment by kfend** [comment]
@kesun1 - Thank you for the feedback. 
@suvaidya - Can you please take a look at this and update the topic?
