### ISSUE TITLE
Error Running Sample Code

### ISSUE THREAD

**Issue by Couchiman** [MicrosoftDocs/dynamics-365-project-operations#27]
ScheduleAPI-AV-0001:a668ff30-2872-ec11-8943-000d3a34a1d1: Input to the column msdyn_progress in the table msdyn_projecttask during create operation is not allowed.'

This is the method

      private OperationSetResponse CallPssCreateAction(Entity entity, string operationSetId)
        {
            OrganizationRequest operationSetRequest = new OrganizationRequest("msdyn_PssCreateV1");
            operationSetRequest["Entity"] = entity;
            operationSetRequest["OperationSetId"] = operationSetId;
            return GetOperationSetResponseFromOrgResponse(organizationService.Execute(operationSetRequest));
        }

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f269741b-6823-92ab-066d-90e68ac3e418
* Version Independent ID: e39d8b04-27e4-9345-5dc5-d752268d04a2
* Content: [Use Project schedule APIs to perform operations with Scheduling entities](https://docs.microsoft.com/en-us/dynamics365/project-operations/project-management/schedule-api-preview)
* Content Source: [articles/project-management/schedule-api-preview.md](https://github.com/MicrosoftDocs/dynamics-365-project-operations-pr/blob/live/articles/project-management/schedule-api-preview.md)
* Service: **dynamics-365-project-operations**
* GitHub Login: @sigitac
* Microsoft Alias: **sigitac**

**Comment by kfend** [comment]
@Couchiman - Thank you for the feedback. 
@sigitac - Can you please take a look and update the topic as necessary? Thanks!

**Comment by kfend** [comment]
The topic has been updated and published.
