### ISSUE TITLE
video cannot be viewed

### ISSUE THREAD

**Issue by martynlesbirel-ashtoncourt** [MicrosoftDocs/dynamics-365-project-operations#28]
The final section of the page offers a link to an overview video.

However this links to a YouTube video that is flagged as private and nothing can be viewed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e1e6e079-1d90-3d44-f3c5-6ff9580ca050
* Version Independent ID: 21c697b3-9d4c-f858-f3eb-74d017e87807
* Content: [What is Dynamics 365 Project Service Automation?](https://docs.microsoft.com/en-us/dynamics365/project-operations/psa/overview)
* Content Source: [articles/psa/overview.md](https://github.com/MicrosoftDocs/dynamics-365-project-operations-pr/blob/live/articles/psa/overview.md)
* Service: **dynamics-365-project-operations**
* GitHub Login: @stsporen
* Microsoft Alias: **ruhercul**

**Comment by kfend** [comment]
@martynlesbirel-ashtoncourt - Thank you for the feedback. 
@ruhercul and @stsporen - Can you please take a look and update the video link?

**Comment by stsporen** [comment]
I've updated the documentation to remove the link. Thanks for the feedback.
