### ISSUE TITLE
Installation was not possible with this Doc

### ISSUE THREAD

**Issue by danielsevinc** [MicrosoftDocs/dynamics-365-project-operations#3]
Hi,

I tried to install the Project Operations trial. I've done everything as described, but there is no possibility to get the Project Operations module if I go to the created "Trial (subscription-based)" environment with the Global Admin User which has the Project Operations and Office 365 Project Operations License assigned.
I really need help here and its also an urgent topic!

Regards
Daniel

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ccf6998-875e-f898-b6dc-f901dfc3ee9b
* Version Independent ID: db331611-34f7-c110-c8fb-83a51c97ec30
* Content: [Sign up for a preview subscription - lite](https://docs.microsoft.com/en-us/dynamics365/project-operations/environment/lite-preview-subscription-sign-up#feedback)
* Content Source: [articles/environment/lite-preview-subscription-sign-up.md](https://github.com/MicrosoftDocs/dynamics-365-project-operations-pr/blob/live/articles/environment/lite-preview-subscription-sign-up.md)
* Service: **project-operations**
* GitHub Login: @sigitac
* Microsoft Alias: **sigitac**

**Comment by kfend** [comment]
@danielsevinc - thank you for the feedback
@sigitac - can you please take a look?

**Comment by sigitac** [comment]
@danielsevinc - we would need to collect more details to understand why this is happening. Please log a support ticket and support engineer will help to troubleshoot.

**Comment by kfend** [comment]
Closing as this is a support issue. @sigitac - thanks for following up.
