### ISSUE TITLE
I think information on this page is outdated 

### ISSUE THREAD

**Issue by NicoBens** [MicrosoftDocs/dynamics-365-project-operations#30]
I use MS Project version "Microsoft® Project® Online Desktop Client MSO (Version 2201 Build 16.0.14827.20198) 64-bit" and I don't find a "Microsoft Dynamics 365" tab in the menu :-(

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7cdfbb9b-121f-a32b-ba9b-98beb028c85c
* Version Independent ID: 3417cb7e-f4f7-c307-c33b-4850e8d489a8
* Content: [Microsoft Project client integration](https://docs.microsoft.com/en-us/dynamics365/project-operations/prod-pma/project-integration)
* Content Source: [articles/prod-pma/project-integration.md](https://github.com/MicrosoftDocs/dynamics-365-project-operations-pr/blob/live/articles/prod-pma/project-integration.md)
* Service: **dynamics-365-project-operations**
* Product: ****
* Technology: ****
* GitHub Login: @Yowelle
* Microsoft Alias: **andchoi**

**Comment by kfend** [comment]
@NicoBens - Thank you for the feedback.
@sigitac - Can you please take a look and update this topic as necessary? Thanks!

**Comment by johnmichalak** [comment]
@NicoBens - I spoke with the PM and she believes the documentation is correct, but suspects that MS Project Add-in for Dynamics 365 Project Operations has not been installed. If you install the Add-in, the tab should display. Unfortunately, we're unable to handle Support requests for the product here if you need further assistance. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.
