### ISSUE TITLE
Task grid is not loading

### ISSUE THREAD

**Issue by rpskumar** [MicrosoftDocs/dynamics-365-project-operations#31]
[Enter feedback here]
Task grid is not loading for some users after trying all the fixes mentioned in the page. We submitted Microsoft support ticket (2110140040007474), the workaround provided is to go to https://project.microsoft.com/ and then try again. After opening project.microsoft.com the task grid is loading. However the session is expiring every 15 minutes and user needs to redo the workaround every time. It is very bad user experience.

Today (3/25/2022) I got response from support team that fix will be expected in end of Q1 2023. There is fundamental issue with Project operation & Project for web integration. Very poorly designed architecture by Microsoft.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9b5cae0-20ce-25f9-12a1-ad1d504142e9
* Version Independent ID: 558c0557-98cc-2070-c83c-759a50b9c533
* Content: [Troubleshoot working in the Task grid](https://docs.microsoft.com/en-us/dynamics365/project-operations/project-management/projectplanningUIFAQ)
* Content Source: [articles/project-management/projectplanningUIFAQ.md](https://github.com/MicrosoftDocs/dynamics-365-project-operations-pr/blob/live/articles/project-management/projectplanningUIFAQ.md)
* Service: **dynamics-365-project-operations**
* GitHub Login: @ruhercul
* Microsoft Alias: **ruhercul**

**Comment by johnmichalak** [comment]
Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, you might want to go to the [Dynamics 365 community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.

**Comment by rpskumar** [comment]
> Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, you might want to go to the [Dynamics 365 community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.

**Comment by rpskumar** [comment]
@johnmichalak  Thank you. I will post there. However the issue and work around solution can be added as troubleshooting guide for others who experience similar experience. MS Documentation page does not have information on this issue

**Comment by johnmichalak** [comment]
This will be added soon. Thank you for the suggestion.
