### ISSUE TITLE
Wrong year

### ISSUE THREAD

**Issue by PeterDNorman** [MicrosoftDocs/dynamics-365-project-operations#32]
This should be 2022 wave 1 **NOT** 2021

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a11b8dd6-96f9-fb36-7000-17a63bad2422
* Version Independent ID: a11b8dd6-96f9-fb36-7000-17a63bad2422
* Content: [Upgrade considerations for Modern Approvals](https://docs.microsoft.com/en-us/dynamics365/project-operations/upgrade/upgrade-considerations-modern-approvals)
* Content Source: [articles/upgrade/upgrade-considerations-modern-approvals.md](https://github.com/MicrosoftDocs/dynamics-365-project-operations-pr/blob/live/articles/upgrade/upgrade-considerations-modern-approvals.md)
* Service: **dynamics-365-project-operations**
* GitHub Login: @stsporen
* Microsoft Alias: **stsporen**

**Comment by johnmichalak** [comment]
Thanks for the feedback. It looks like the into says 2022 Wave 1.
