### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by Cosmosis22** [MicrosoftDocs/dynamics-365-project-operations#33]
Type in title header: pnvoice should be invoice

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f71b222-47ab-b207-a8fb-fc6a63ef734a
* Version Independent ID: 385f4c27-e0dc-7920-bc6d-f34d65be6fdc
* Content: [Proforma project invoices](https://docs.microsoft.com/en-us/dynamics365/project-operations/pro/proforma-invoicing/create-manual-proforma-invoice-sales)
* Content Source: [articles/pro/proforma-invoicing/create-manual-proforma-invoice-sales.md](https://github.com/MicrosoftDocs/dynamics-365-project-operations-pr/blob/live/articles/pro/proforma-invoicing/create-manual-proforma-invoice-sales.md)
* Service: **dynamics-365-project-operations**
* Product: ****
* GitHub Login: @rumant
* Microsoft Alias: **rumant**

**Comment by johnmichalak** [comment]
Thank you for the feedback, we will get this fixed right away!
