### ISSUE TITLE
Cannot open Task grid in Teams

### ISSUE THREAD

**Issue by rajatk09** [MicrosoftDocs/dynamics-365-project-operations#34]
![image](https://user-images.githubusercontent.com/97608110/164201834-082531bf-2178-4f4d-af22-253b3f4bf1fb.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9b5cae0-20ce-25f9-12a1-ad1d504142e9
* Version Independent ID: 558c0557-98cc-2070-c83c-759a50b9c533
* Content: [Troubleshoot working in the Task grid](https://docs.microsoft.com/en-us/dynamics365/project-operations/project-management/projectplanningUIFAQ)
* Content Source: [articles/project-management/projectplanningUIFAQ.md](https://github.com/MicrosoftDocs/dynamics-365-project-operations-pr/blob/live/articles/project-management/projectplanningUIFAQ.md)
* Service: **dynamics-365-project-operations**
* GitHub Login: @ruhercul
* Microsoft Alias: **ruhercul**

**Comment by johnmichalak** [comment]
@rajatk09 Thank you for the feedback.
@ruhercul Russel, can you take a look at this and update the topic if needed?
