### ISSUE TITLE
Broken Link to Finance Trial?

### ISSUE THREAD

**Issue by standswell** [MicrosoftDocs/dynamics-365-project-operations#35]
[Enter feedback here]

Could you please check that the link for a Finance trial is correct?  If I follow https://aka.ms/trypoce, it appears to be broken.
---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a8e0a73-6f79-8869-a41d-d17c360faf57
* Version Independent ID: b09df2b0-0065-d3c8-74d6-e3c314bca1e2
* Content: [Sign up for Project Operations preview subscriptions for resource/ non-stocked scenarios](https://docs.microsoft.com/en-gb/dynamics365/project-operations/environment/resource-sign-up-preview-subscription)
* Content Source: [articles/environment/resource-sign-up-preview-subscription.md](https://github.com/MicrosoftDocs/dynamics-365-project-operations-pr/blob/live/articles/environment/resource-sign-up-preview-subscription.md)
* Service: **dynamics-365-project-operations**
* GitHub Login: @sigitac
* Microsoft Alias: **sigitac**

**Comment by johnmichalak** [comment]
@standswell the link has been corrected and should be aka.ms/try-po
