### ISSUE TITLE
D356 Finance

### ISSUE THREAD

**Issue by makdaddy8888** [MicrosoftDocs/dynamics-365-project-operations#36]
So is a D365 Finance license required or can PO send invoices?

What happens in you don't want to use D365F and want a simple accounting package to post journals?
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2f01905-f745-68a7-cbeb-4dacaec137bc
* Version Independent ID: cd08aaa1-a3dc-7b62-6b18-15dcc205d0bd
* Content: [Invoicing process overview](https://docs.microsoft.com/en-us/dynamics365/project-operations/invoicing/post-project-invoices)
* Content Source: [articles/invoicing/post-project-invoices.md](https://github.com/MicrosoftDocs/dynamics-365-project-operations-pr/blob/live/articles/invoicing/post-project-invoices.md)
* Service: **dynamics-365-project-operations**
* GitHub Login: @sigitac
* Microsoft Alias: **sigitac**

**Comment by johnmichalak** [comment]
@sigitac Can you help with these questions?
