### ISSUE TITLE
E_INVALIDENTITYUID : Invalid item id Error While using schedule-api

### ISSUE THREAD

**Issue by sudershankh** [MicrosoftDocs/dynamics-365-project-operations#37]
I am trying to bulk delete project tasks with "CallPssDeleteAction" , Each operation set will contain maximum of 97 tasks . but This error pops up randomly ,
`{"code":"-1945829329","message":"{\"errorId\":-1945829329,\"errorKey\":\"E_BATCHFAILED\",\"ErrorMessage\":\"One of the batch requests failed\",\"failedBatchRequestIndex\":0,\"failedBatchRequestError\":{\"errorId\":-1946156705,\"errorKey\":\"E_INVALIDENTITYUID\",\"ErrorMessage\":\"Invalid item id\"}}","innerError":null}` ,
 
if retried after some time it works and then again throws an error. Is there any other way to bulk delete all project Tasks

**Comment by johnmichalak** [comment]
Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.
