### ISSUE TITLE
Contradictory text, with suggested wording.

### ISSUE THREAD

**Issue by jimwillsher** [MicrosoftDocs/dynamics-365-project-operations#38]
[Enter feedback here]

The text near the top is contradictory.

Dynamics 365 Project Operations consists of two components:

Project Operations on Dataverse environment covers capabilities from opportunity to proforma invoicing. **Dataverse is used in the lite deployment and resource/non-stocked scenarios** deployment of Project Operations.
Project management and accounting in the Dynamics 365 Finance environment covers expense management capabilities, project accounting, and revenue recognition. The **Finance and Operations app environment is used in Project Operations for resource/non-stocked** based scenarios and Project Operations for stocked/production-based scenarios.

Th second sentence is the incorrect one. Dataverse (PSA, CE etc) has no capability for stock items. So the sentence should read:

The Finance and Operations app environment is used in Project Operations for stocked/production-based based scenarios and Project Operations on Dataverse for resource/non-stocked scenarios.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e3b959a-3556-eafe-a4f9-d0f499140a4d
* Version Independent ID: 30d4eb1c-4d5c-271b-1947-eb87bcc18ce3
* Content: [Project Operations updates](https://docs.microsoft.com/en-us/dynamics365/project-operations/whats-new/project-operations-updates)
* Content Source: [articles/whats-new/project-operations-updates.md](https://github.com/MicrosoftDocs/dynamics-365-project-operations-pr/blob/live/articles/whats-new/project-operations-updates.md)
* Service: **dynamics-365-project-operations**
* Product: ****
* GitHub Login: @sigitac
* Microsoft Alias: **sigitac**

**Comment by johnmichalak** [comment]
@jimwillsher Thanks for letting us know. We are investigating this issue. 
@sigitac Please review the suggestion and let me know if I can implement it as suggested?

**Comment by sigitac** [comment]
I think what is in the original text is correct.
"The Finance and Operations app environment is used in Project Operations for resource/non-stocked based scenarios and Project Operations for stocked/production-based scenarios."

Yellow are the names of the deployment modes. Both of these deployment modes use Finance and Operations app environment.
I am happy to reword, John if you have alternatives, but we should stick to official deployment names.

Thanks
sigita

**Comment by johnmichalak** [comment]
Closing the issue, as mentioned by Sigita the statements are correct.
