### ISSUE TITLE
Incorrect branding

### ISSUE THREAD

**Issue by mjcorkery** [MicrosoftDocs/dynamics-365-project-operations#39]
This article refers to Common Data Service, but this term was replaced with Microsoft Dataverse in 2021.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f90e4213-1841-7388-563f-432ad0904bad
* Version Independent ID: cb9511f8-2192-4376-edca-328cf3b1cdb5
* Content: [Set up and apply configuration data in the Common Data Service](https://docs.microsoft.com/en-us/dynamics365/project-operations/environment/resource-apply-pro-setup-config-data)
* Content Source: [articles/environment/resource-apply-pro-setup-config-data.md](https://github.com/MicrosoftDocs/dynamics-365-project-operations-pr/blob/live/articles/environment/resource-apply-pro-setup-config-data.md)
* Service: **dynamics-365-project-operations**
* GitHub Login: @sigitac
* Microsoft Alias: **sigitac**

**Comment by johnmichalak** [comment]
@sigitac Should this be changed to Microsoft Dataverse as suggested?

**Comment by johnmichalak** [comment]
@mjcorkery Thank you for letting us know. This topic has been updated.
