### ISSUE TITLE
Please update to reflect current functiuonality

### ISSUE THREAD

**Issue by pbonny1** [MicrosoftDocs/dynamics-365-project-operations#4]
1. There does not appear to be any option 'what is this project for?'
2. As soon as product name 'Finance and Opns ' selected, methodology selection disappears 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49b9ad1b-4b96-679b-318b-0fd8a7d322b6
* Version Independent ID: eae36628-bb7d-442a-2725-4d532b815af8
* Content: [Start a new LCS project](https://docs.microsoft.com/en-us/dynamics365/project-operations/environment/create-lcs-project)
* Content Source: [articles/environment/create-lcs-project.md](https://github.com/MicrosoftDocs/dynamics-365-project-operations-pr/blob/live/articles/environment/create-lcs-project.md)
* Service: **project-operations**
* GitHub Login: @stsporen
* Microsoft Alias: **stsporen**

**Comment by stsporen** [comment]
Hi,

I took a look at the flow, which part of step four do you believe is wrong? 

Thanks

**Comment by pbonny1** [comment]
Hi,

It seems that step 4 no longer exists when I click on the plus sign to create a new project

Cheers
