### ISSUE TITLE
Instructions to uninstall Project Operations don’t work

### ISSUE THREAD

**Issue by markheydon** [MicrosoftDocs/dynamics-365-project-operations#40]
Instructions don’t actually work as there’s a dependency to msdynce_ActivitiesPatch when you try uninstall ProjectService. Something between Process Notes table and Process Notes Chat.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: febd2933-2948-df9c-af3f-0a558b56fb13
* Version Independent ID: febd2933-2948-df9c-af3f-0a558b56fb13
* Content: [Uninstall Dynamics 365 Project Operations](https://docs.microsoft.com/en-us/dynamics365/project-operations/environment/uninstall-project-operations#:~:text=Uninstall%20Dynamics%20365%20Project%20Operations.%201%20Go%20to,they%20are%20listed%20in%20the%20following%20table.%20)
* Content Source: [articles/environment/uninstall-project-operations.md](https://github.com/MicrosoftDocs/dynamics-365-project-operations-pr/blob/live/articles/environment/uninstall-project-operations.md)
* Service: **dynamics-365-project-operations**
* GitHub Login: @stsporen
* Microsoft Alias: **sigitac**

**Comment by johnmichalak** [comment]
@stsporen Can you please review this suggestion to see if the article should be updated?

**Comment by markheydon** [comment]
Bit of an update on this, since raising this issue: I have now had a support ticket open with the Dynamics 365 support team. Their initial response below I don't quite understand fully in all honesty, it makes references to 'custom entity', of which I have none so honestly not sure if they are saying the error was unique to my environment or it's going to happen to every environment, presumably where the new Teams stuff gets enabled.

> ...when a custom entity is marked as hasactivity -> isActivityParty and activities_patch solution gets installed, teamsChat entity creation triggers activityparty relationship with this entity and the relationship is created in the Activities_Patch layer instead of the active layer.
> 
> This then blocks entity delete/solution uninstall as there is a relationship which is in the Activities_path layer.

Either way, support had to run some script to 'fix' the issue before I was able to then follow the instructions in the article. So, if that's the case for everybody, those instructions will never work without involving support?
