### ISSUE TITLE
Mention of "Team Member details" is ambiguous

### ISSUE THREAD

**Issue by anttipajunen** [MicrosoftDocs/dynamics-365-project-operations#41]
Hi @rumant. I think [this](https://docs.microsoft.com/en-us/dynamics365/project-operations/pro/subcontracting/subcontracting-project-team-members#subcontracting-an-unstaffed-project-team-member) page and its definition of a **Team Member details** page could be revised. Team Member details is ambiguous as we don't have such a specific page in ProjOps that I could find. It probably refers to the PTM main and quick create forms, which have columns for subcontract and subcon line?

Edited July 29th for typos.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf43cf75-a45f-cd84-1845-a69645f9dfdc
* Version Independent ID: bf43cf75-a45f-cd84-1845-a69645f9dfdc
* Content: [Subcontracting project team members](https://docs.microsoft.com/en-us/dynamics365/project-operations/pro/subcontracting/subcontracting-project-team-members)
* Content Source: [articles/pro/subcontracting/subcontracting-project-team-members.md](https://github.com/MicrosoftDocs/dynamics-365-project-operations-pr/blob/live/articles/pro/subcontracting/subcontracting-project-team-members.md)
* Service: **dynamics-365-project-operations**
* GitHub Login: @rumant
* Microsoft Alias: **rumant**

**Comment by johnmichalak** [comment]
@rumant Can you take a look at this request to see if changes should be made?
