### ISSUE TITLE
Incorrect table name

### ISSUE THREAD

**Issue by johnsonmattMS** [MicrosoftDocs/dynamics-365-project-operations#43]
The name of the table "Project Operations integration table for material estimates" is wrong. It should be "Project integration table for material estimates"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50270634-66ca-3f43-8c02-472619ac2a8e
* Version Independent ID: 428597ee-5b17-d0af-55ed-b66edbb3ed58
* Content: [Project Operations dual-write map versions](https://docs.microsoft.com/en-us/dynamics365/project-operations/environment/resource-dual-write-maps)
* Content Source: [articles/environment/resource-dual-write-maps.md](https://github.com/MicrosoftDocs/dynamics-365-project-operations-pr/blob/live/articles/environment/resource-dual-write-maps.md)
* Service: **dynamics-365-project-operations**
* GitHub Login: @sigitac
* Microsoft Alias: **sigitac**

**Comment by johnmichalak** [comment]
@johnsonmattMS Thanks for the feedback!

@sigitac Is it okay if I make this change?

**Comment by sigitac** [comment]
Yes, please. Thank you, Matt and John.

**Comment by johnmichalak** [comment]
The changes have been made and will be published overnight.
