### ISSUE TITLE
Step 13: Create a resource assignment doesn't work

### ISSUE THREAD

**Issue by pablop2006** [MicrosoftDocs/dynamics-365-project-operations#44]
it always throws the annoying "Resource not found for the segment" error. No matter what.
The only way to make it work is by setting up a custom connector.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84c82000-5728-b3d3-f66d-72283c511bc0
* Version Independent ID: 84c82000-5728-b3d3-f66d-72283c511bc0
* Content: [Use Project schedule APIs with Power Automate](https://docs.microsoft.com/en-us/dynamics365/project-operations/project-management/scheduling-apis-powerautomate)
* Content Source: [articles/project-management/scheduling-apis-powerautomate.md](https://github.com/MicrosoftDocs/dynamics-365-project-operations-pr/blob/live/articles/project-management/scheduling-apis-powerautomate.md)
* Service: **dynamics-365-project-operations**
* GitHub Login: @ruhercul
* Microsoft Alias: **ruhercul**

**Comment by johnmichalak** [comment]
@pablop2006 Thank you for the feedback!

@ruhercul Can you please check the documentation to see if additional content is needed or corrections need to be made?

**Comment by johnmichalak** [comment]
Published a fix for this. A typo was found on line 245 "@@odata.type"
