### ISSUE TITLE
Could you formulate description of fixes in an unambiguous way, so that it is clear what in an incorrect behaviour and what is a correct behaviour

### ISSUE THREAD

**Issue by maciejlazowski** [MicrosoftDocs/dynamics-365-project-operations#45]
[Enter feedback here]
https://docs.microsoft.com/en-us/dynamics365/project-operations/psa/whats-new-ur-38

Example:
_Bug fixes
The following issues have been fixed.
'Negative sales amounts aren't allowed on Project and Task entities.'_

Is the sentence above describing the bug or the new behaviour?

Such ambiguous statements are used much too often and lead to client confusion and consultants spending too much time analyzing what the author meant. Please try to read it assuming the reader does not know the context. Please try using positive sentences such as: User can now create Projects and Tasks with a negative sales amount etc. Try using active voice rather than passive voice in these sentences also and avoid negations. This would help a lot. 

Thank you

Matthew Lazowski

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4c5bca1-aa9d-beaf-963c-6466b5a8fcfd
* Version Independent ID: e4c5bca1-aa9d-beaf-963c-6466b5a8fcfd
* Content: [What's new or changed in Project Service Automation Update Release 38, V3](https://docs.microsoft.com/en-us/dynamics365/project-operations/psa/whats-new-ur-38)
* Content Source: [articles/psa/whats-new-ur-38.md](https://github.com/MicrosoftDocs/dynamics-365-project-operations-pr/blob/live/articles/psa/whats-new-ur-38.md)
* Service: **dynamics-365-project-operations**
* GitHub Login: @ruhercul
* Microsoft Alias: **ruhercul**

**Comment by johnmichalak** [comment]
@maciejlazowski Thank you for the feedback.

@ruhercul Does 'Negative sales amounts aren't allowed on Project and Task entities.' describe the defect or the new behavior that has been included in this release?
