### ISSUE TITLE
Can we apply Delegates or "on behalf of" for users to create travel requisition?

### ISSUE THREAD

**Issue by khanmd21** [MicrosoftDocs/dynamics-365-project-operations#48]
[Enter feedback here]
questions: 
Can we apply Delegates or "on behalf of" for users to create travel requisition?

Current users can create expense report by "Delegate". Can D365 have this function for Travel advance as well?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d208ff34-af34-d887-fb9d-47469940dd79
* Version Independent ID: 9bcf4912-55a2-82ee-c073-bd0118276231
* Content: [Travel requisitions](https://docs.microsoft.com/en-us/dynamics365/project-operations/expense/travel-requisition#feedback)
* Content Source: [articles/expense/travel-requisition.md](https://github.com/MicrosoftDocs/dynamics-365-project-operations/blob/main/articles/expense/travel-requisition.md)
* Service: **dynamics-365-project-operations**
* GitHub Login: @suvaidya
* Microsoft Alias: **suvaidya**

**Comment by johnmichalak** [comment]
@ramagadu Can you help answer this question?

**Comment by ramagadu** [comment]
Hey @johnmichalak , Yes, the Delegates works for travel requestions as well.
