### ISSUE TITLE
Screenshots fuzzy

### ISSUE THREAD

**Issue by AjayOdedra** [MicrosoftDocs/dynamics-365-project-operations#5]
Most of the screenshots on this page are so poor quality that the text is not legible, can you please update them?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51dfaa6b-0294-a3c9-d134-ad6811b34540
* Version Independent ID: e22ab93a-6a24-510c-685e-b0d6d905c2ab
* Content: [Provision a new environment](https://docs.microsoft.com/en-us/dynamics365/project-operations/environment/resource-provision-new-environment)
* Content Source: [articles/environment/resource-provision-new-environment.md](https://github.com/MicrosoftDocs/dynamics-365-project-operations-pr/blob/live/articles/environment/resource-provision-new-environment.md)
* Service: **project-operations**
* Product: ****
* GitHub Login: @sigitac
* Microsoft Alias: **sigitac**

**Comment by kfend** [comment]
@AjayOdedra - thank you for the feedback.
@sigitac - please take a look at and address this.

**Comment by kfend** [comment]
Closing as we don't have access to the screenshots.
