### ISSUE TITLE
Build number is wrong

### ISSUE THREAD

**Issue by mjfjesus** [MicrosoftDocs/dynamics-365-project-operations#6]
Build number should be 3.10.47.x

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cab19b75-0e12-aeaf-590f-967b75501f92
* Version Independent ID: 1ef0f307-d4c5-7b0f-96d9-9400b6b741a2
* Content: [What's new or changed in Project Service Automation Update Release 29, V3](https://docs.microsoft.com/en-us/dynamics365/project-operations/psa/whats-new-ur-29)
* Content Source: [articles/psa/whats-new-ur-29.md](https://github.com/MicrosoftDocs/dynamics-365-project-operations-pr/blob/live/articles/psa/whats-new-ur-29.md)
* Service: **project-operations**
* GitHub Login: @ruhercul
* Microsoft Alias: **ruhercul**

**Comment by kfend** [comment]
@mjfjesus - thank you for the feedback. 
@ruhercul - can you please take a look at and address this?

**Comment by kfend** [comment]
We have updated and republished the topic.
