### ISSUE TITLE
Initiate upgrade docs page step 4 is not clear

### ISSUE THREAD

**Issue by anttipajunen** [MicrosoftDocs/dynamics-365-project-operations#60]
Hi @ruhercul 

Page at:
https://learn.microsoft.com/en-us/dynamics365/project-operations/psa/upgrade-project-operations-non-stocked#initiate-upgrade

Section:
4. Go to Settings > Solutions, and select to uninstall the Project Operations Deprecated Components solution.

Issue:
Should this state that the Project Operations Deprecated Components solution is deleted from the make portal at make.powerapps.com -> solutions -> select and delete the solution?

![image](https://user-images.githubusercontent.com/64043240/198900138-807c23c5-b980-4557-b66d-dba920a89b75.png)

**Comment by johnmichalak** [comment]
@anttipajunen Changes have been made and were merged. They should go live later today. Thank you!
