### ISSUE TITLE
Designate a new time entry status as read-only

### ISSUE THREAD

**Issue by ahmadpirani** [MicrosoftDocs/dynamics-365-project-operations#64]
No actual steps and where to do it is provided. Only 'just do this'.

"To designate a new time entry status as read-only, add the new time entry value to the Read-only Status List property. Be sure to add the number, not the label. The editable part of the time entry grid will now be locked for rows that have the new status. To set the Read-only Status List property differently for different Time Entry views, add the Time entry grid in a view's Custom controls section, and configure the parameters as appropriate.

Next, add business rules to lock all the fields on the Row edit and Time entry edit pages. To access the business rules for these pages, open the form editor for each page, and then select Business rules. You can add the new status to the condition in the existing business rules, or you can add a new business rule for the new status."

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f01669b3-514a-9ab6-d441-668f24d50852
* Version Independent ID: aa901bf3-c116-eaa5-dcd8-2c99be38d312
* Content: [Extending time entries](https://learn.microsoft.com/en-us/dynamics365/project-operations/time/customize-weekly-time-entry-grid)
* Content Source: [articles/time/customize-weekly-time-entry-grid.md](https://github.com/MicrosoftDocs/dynamics-365-project-operations/blob/main/articles/time/customize-weekly-time-entry-grid.md)
* Service: **dynamics-365-project-operations**
* GitHub Login: @stsporen
* Microsoft Alias: **stsporen**

**Comment by johnmichalak** [comment]
@ahmadpirani Thank you for the feedback. I will reach out to the author to see if revisions can be made in the future.
