### ISSUE TITLE
Timesheet App compatibility

### ISSUE THREAD

**Issue by Sigvelli** [MicrosoftDocs/dynamics-365-project-operations#67]
The sentence "This mobile application is compatible with iPhone with Platform update 15. Android will be compatible with Platform update 16, when it becomes available." is misleading.

The Timesheet App require Iphones  iOS 9.3 or later or Android 9 or later.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6c72db50-d884-033f-78d1-dc86281009e6
* Version Independent ID: d2780d61-9fae-4d26-fc33-13fe0a7e3847
* Content: [Project timesheets on a mobile device](https://learn.microsoft.com/en-us/dynamics365/project-operations/prod-pma/mobile-timesheets)
* Content Source: [articles/prod-pma/Mobile-timesheets.md](https://github.com/MicrosoftDocs/dynamics-365-project-operations/blob/main/articles/prod-pma/Mobile-timesheets.md)
* Service: **dynamics-365-project-operations**
* Product: ****
* Technology: ****
* GitHub Login: @abruer
* Microsoft Alias: **abruer**

**Comment by johnmichalak** [comment]
@Sigvelli Can you provide more information about why this is misleading? I will get with the author to see if changes can be made to make it clearer. Thank you!

**Comment by Sigvelli** [comment]
“This mobile application is compatible with iPhone with Platform update 15. 
Android will be compatible with Platform update 16, when it becomes available.”

Which “platform update” is the article referring to? 

If you have an IPhone I guess “Platform Update 15” is “IOS 15”.
But from an Android point of view, the next sentence is more difficult to understand: “Android will be compatible with Platform update 16, when it becomes available.”
My phone has Android versjon 13, and the app is working perfect. (Timesheet version: 1.26.3)

**Comment by johnmichalak** [comment]
The platform update refers to the Dynamics 365 platform update and not the version of the phone operating system that you are using. However, your phone operating system must be iOS 9.3 or later or Android 9 or later.
