### ISSUE TITLE
Version information issue

### ISSUE THREAD

**Issue by stuartahonour** [MicrosoftDocs/dynamics-365-project-operations#7]
Is the information on this page correct?

I think the version information is incorrect

Project Operations on Dataverse environment version **4.8.0.91**
Project management and accounting on Dynamics 365 Finance environment version **10.0.16**

Should this be 

Project Operations on Dataverse environment version **4.8.0.92**
Project management and accounting on Dynamics 365 Finance environment version **10.0.17**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8e9fc52-b953-62a2-5c10-23f8fa57934e
* Version Independent ID: 57bd41e6-875a-3327-21cd-38f7a90bf63e
* Content: [What's new March 2021 - Project Operations for resource/non-stocked based scenarios](https://docs.microsoft.com/en-us/dynamics365/project-operations/whats-new/whats-new-mar-2021-resource-based)
* Content Source: [articles/whats-new/whats-new-mar-2021-resource-based.md](https://github.com/MicrosoftDocs/dynamics-365-project-operations-pr/blob/live/articles/whats-new/whats-new-mar-2021-resource-based.md)
* Service: **project-operations**
* Product: ****
* GitHub Login: @sigitac
* Microsoft Alias: **sigitac**

**Comment by kfend** [comment]
@sigitac - can you please take a look at this?

**Comment by sigitac** [comment]
Build numbers were corrected at a time, no update needed.

**Comment by kfend** [comment]
Thanks @sigitac!
