### ISSUE TITLE
Update Project Label Text 

### ISSUE THREAD

**Issue by pcrozer** [MicrosoftDocs/dynamics-365-project-operations#72]
Hi, I'm struggling to execute the msdyn_PssUpdateV1 operation on msdyn_projectlabel. 
Could you provide an example, or help identify what's wrong with what I'm doing?
(I'm able to do it on msdyn_projecttask successfully, but trying to update msdyn_projectlabeltext on msdyn_projectlabel is my issue)

I can query the project labels successfully, and so get a msdyn_projectlabelid value for which I want to change the text.

Then I create an operation set with msdyn_CreateOperationSetV1
Then I'm posting the data below to msdyn_PssUpdateV1 (with appropriate ids substituted)

```
{
    "Entity": {
        "msdyn_projectlabeltext": "Test Label 1",
        "@odata.type": "Microsoft.Dynamics.CRM.msdyn_projectlabel",
        "msdyn_projectid@odata.bind": "msdyn_projects({{projectId}})",
        "msdyn_projectlabelid": "{{projectLabelId}}"
    },
    "OperationSetId": "{{operationSetId}}"
}
```

and then call msdyn_ExecuteOperationSetV1

But the response is as if I'm attempting a direct update on the project:

```
{
    "status": 0,
    "message": "https:\/\/org8442c39e.api.crm4.dynamics.com\/api\/data\/v9.1\/msdyn_ExecuteOperationSetV1",
    "originaldata": {
        "error": {
            "code": "0x80040265",
            "message": "We\u2019re sorry. You cannot directly do 'Update' operation to 'msdyn_project'. Try editing it through the Resource editing UI via Project."
        }
    }
}

```
Do you know why?  What's the correct operation set content for updating a project label?
Many thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f269741b-6823-92ab-066d-90e68ac3e418
* Version Independent ID: e39d8b04-27e4-9345-5dc5-d752268d04a2
* Content: [Use Project schedule APIs to perform operations with Scheduling entities](https://learn.microsoft.com/en-us/dynamics365/project-operations/project-management/schedule-api-preview)
* Content Source: [articles/project-management/schedule-api-preview.md](https://github.com/MicrosoftDocs/dynamics-365-project-operations/blob/main/articles/project-management/schedule-api-preview.md)
* Service: **dynamics-365-project-operations**
* GitHub Login: @sigitac
* Microsoft Alias: **sigitac**

**Comment by johnmichalak** [comment]
@pcrozer Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.

**Comment by grale88** [comment]
Hi @pcrozer 

Did you manage to resolve your issue? I am having a similar one with inserting label to task assignments (msdyn_projecttasktolabel). I've reported it on dynamics community - https://community.dynamics.com/365/project-operations/f/dynamics-365-project-operations-forum/474953/cannot-insert-project-task-to-label-entities

@johnmichalak It would be great if you could provide a code example for working with labels and task to label assignments as part of your Schedule API documentation page.

Best regards

**Comment by jeppesc11** [comment]
I get the same error - anyone found a solution?

**Comment by pcrozer** [comment]
Hi @grale88 

Sadly not, I posted on dynamics community months ago, but so far there is no sign of any community!

[https://community.dynamics.com/crm/f/microsoft-dynamics-crm-forum/471660/update-project-label-text-via-dynamics-api](url)
