### ISSUE TITLE
Need more documention

### ISSUE THREAD

**Issue by russellmccloy** [MicrosoftDocs/dynamics-365-project-operations#73]
Hi there,

I am working on a very important project for my company and we hare deciding whether to use Project Online for some functionality we need.

Just about the only useful documentation I can find on the internet is the following page:
https://learn.microsoft.com/en-us/dynamics365/project-operations/project-management/schedule-api-preview
Which is the bare minimum. I have got the sample code from this page working but I can't find anything on the following:
- add custom field
- update custom field
- set label
- attach file

There has got to be more information somewhere but it is impossible to find.

cheers
Russ

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f269741b-6823-92ab-066d-90e68ac3e418
* Version Independent ID: e39d8b04-27e4-9345-5dc5-d752268d04a2
* Content: [Use Project schedule APIs to perform operations with Scheduling entities](https://learn.microsoft.com/en-us/dynamics365/project-operations/project-management/schedule-api-preview)
* Content Source: [articles/project-management/schedule-api-preview.md](https://github.com/MicrosoftDocs/dynamics-365-project-operations/blob/main/articles/project-management/schedule-api-preview.md)
* Service: **dynamics-365-project-operations**
* GitHub Login: @sigitac
* Microsoft Alias: **sigitac**

**Comment by johnmichalak** [comment]
@russellmccloy Are you wanting to do those things using the API, or are you asking how to do it using the UI? For example, is this the information you are looking for: https://learn.microsoft.com/en-us/dynamics365/project-operations/pricing-costing/add-custom-fields-price-setup-transactional-entities?

**Comment by johnmichalak** [comment]
Closing, no response from russellmccloy.
