### ISSUE TITLE
Specify custom fields for copy project not working

### ISSUE THREAD

**Issue by grale88** [MicrosoftDocs/dynamics-365-project-operations#77]
Hi,

I followed the instructions on how to initiate project copying. The process is working fine but custom columns that are added to "Copy Project Columns View" are not taken into account. Also if I remove a default column (e.g. Start Date) it also gets copied from the source project?

Can you explain in details how this customization should be done, or if this feature is currently not supported please remove it from the documentation page.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4cdc2125-bf2a-985a-d44f-6449a469636a
* Version Independent ID: 5cdec51a-7530-a40f-cc70-6d3e7a838f76
* Content: [Develop project templates with Copy Project](https://learn.microsoft.com/en-us/dynamics365/project-operations/project-management/dev-copy-project)
* Content Source: [articles/project-management/dev-copy-project.md](https://github.com/MicrosoftDocs/dynamics-365-project-operations/blob/main/articles/project-management/dev-copy-project.md)
* Service: **dynamics-365-project-operations**
* GitHub Login: @stsporen
* Microsoft Alias: **stsporen**

**Comment by johnmichalak** [comment]
@grale88 Thank you for the feedback. I will reach out to the author to see if changes are needed to the article.

**Comment by stsporen** [comment]
Checking on this, Fields added to the view should be copied. If this is not happening for you, please log a support ticket to have support take a look.
