### ISSUE TITLE
How to obtain the Schedule API

### ISSUE THREAD

**Issue by ricetristan** [MicrosoftDocs/dynamics-365-project-operations#8]
How do we download/obtain the Schedule API library referenced in this article?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f269741b-6823-92ab-066d-90e68ac3e418
* Version Independent ID: e39d8b04-27e4-9345-5dc5-d752268d04a2
* Content: [Use Schedule APIs to perform operations with Scheduling entities](https://docs.microsoft.com/en-us/dynamics365/project-operations/project-management/schedule-api-preview)
* Content Source: [articles/project-management/schedule-api-preview.md](https://github.com/MicrosoftDocs/dynamics-365-project-operations-pr/blob/live/articles/project-management/schedule-api-preview.md)
* Service: **project-operations**
* GitHub Login: @sigitac
* Microsoft Alias: **sigitac**

**Comment by kfend** [comment]
@ricetristan - thank you for the question.
@sigitac - can you please take a look and address this question?

**Comment by ruhercul** [comment]
We currently do not have more documentation beyond what is provided in this article.  In the coming weeks we will be expanding this article to cover benchmarking and scenarios for Power Automate.

**Comment by johndcollins** [comment]
It's been way longer than a couple of weeks. When can we expect more information on how to use this API?

**Comment by ruhercul** [comment]
> It's been way longer than a couple of weeks. When can we expect more information on how to use this API?

Can you please clarify your specific request?

**Comment by johndcollins** [comment]
Sure.
I'm referring to this page: 
https://docs.microsoft.com/en-us/dynamics365/project-operations/project-management/schedule-api-preview

1. The sample code on the page is not complete. There should be instructions on how to add the packages and which packages to add in a sample project.
2. The code does not work. It fails to execute here:
      assignment["msdyn_start"] = DateTime.Now;
      assignment["msdyn_finish"] = DateTime.Now;

We need to be able to assign time per task to different resources and we are not allowed to. According to this sample code, we should be able to, but we get an error that we are not allowed to change this. How are we supposed to manage resources by task?

John

**Comment by ruhercul** [comment]
> Sure. I'm referring to this page: https://docs.microsoft.com/en-us/dynamics365/project-operations/project-management/schedule-api-preview
> 
> 1. The sample code on the page is not complete. There should be instructions on how to add the packages and which packages to add in a sample project.
> 2. The code does not work. It fails to execute here:
>    assignment["msdyn_start"] = DateTime.Now;
>    assignment["msdyn_finish"] = DateTime.Now;
> 
> We need to be able to assign time per task to different resources and we are not allowed to. According to this sample code, we should be able to, but we get an error that we are not allowed to change this. How are we supposed to manage resources by task?

Thanks John.   we actually do not support the ability to programmatically define the dates or effort of individual resource assignments.   This is something we are working on in 2022.    Today, you can create assignments by specifying the team member and the task, but everything else is calculated based on the scalar value effort on the task and its associated start and end dates.   If you have further questions on this, you can reach to me and we can schedule a call.  Thanks.

**Comment by johndcollins** [comment]
Thanks for the reply.
We reported problems assigning hours in the UI and was directed to this page. We were told we could do this through the API, but apparently that is not the case. We are unable to utilize the Project Operations in it's current state as we need to be able to assign specific hours to resources. I hope this will be a high priority for your team as this is something we need for all our customers.

**Comment by johndcollins** [comment]
Also, you might want to update the code to reflect what is possible. The current code fails and will not work.
