### ISSUE TITLE
"Project Operations doesn't support estimates of materials or fees on projects."

### ISSUE THREAD

**Issue by MateRadz** [MicrosoftDocs/dynamics-365-project-operations#87]
fees word is not straightforward here. Does it mean that created estimate using Project Only will result in inability to get Sales estimates calculated on the project under the "Time phase by" selector (cost/sales)? Or fees refers to something else?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c40dcff6-3fcf-4904-e319-6b05f6af63aa
* Version Independent ID: 2bd78382-b52c-a7cd-dc21-544e5dda356f
* Content: [Financial estimation concepts](https://learn.microsoft.com/en-us/dynamics365/project-operations/project-management/estimating-projects-overview)
* Content Source: [articles/project-management/estimating-projects-overview.md](https://github.com/MicrosoftDocs/dynamics-365-project-operations/blob/main/articles/project-management/estimating-projects-overview.md)
* Service: **dynamics-365-project-operations**
* GitHub Login: @rumant
* Microsoft Alias: **rumant**

**Comment by johnmichalak** [comment]
@rumant Can you please review the suggestion and make any changes that are appropriate?

**Comment by johnmichalak** [comment]
@MateRadz Thank you for the feedback. I will contact the author to see if these revisions can be made.
