### ISSUE TITLE
"Something went wrong" error after adding the subscription id

### ISSUE THREAD

**Issue by jlabustro** [MicrosoftDocs/dynamics-365-project-operations#88]
Good day!

"Something went wrong" error shows up when entering the Azure subscription id in the LCS project, what does that mean?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cdc0447c-b010-64c9-070c-aa208f9fafe1
* Version Independent ID: f65bf115-16f2-be87-5fd5-6542bfd6c0bd
* Content: [Add an Azure subscription to an LCS project](https://learn.microsoft.com/en-us/dynamics365/project-operations/environment/resource-add-azure-subscription-lcs-project)
* Content Source: [articles/environment/resource-add-azure-subscription-lcs-project.md](https://github.com/MicrosoftDocs/dynamics-365-project-operations/blob/main/articles/environment/resource-add-azure-subscription-lcs-project.md)
* Service: **dynamics-365-project-operations**
* GitHub Login: @sigitac
* Microsoft Alias: **sigitac**

**Comment by johnmichalak** [comment]
Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.
