### ISSUE TITLE
Create a generic team member - Action Name field, select TeamMemberAction does not exist

### ISSUE THREAD

**Issue by paul-a-hancock** [MicrosoftDocs/dynamics-365-project-operations#92]
Action seems to have changed to "msdyn_CreateTeamMemberV1" with a signficantly more complex list of parameters. Can the documentation be updated to reflect updated action.

**Comment by johnmichalak** [comment]
@paul-a-hancock Can you share with me which document you would like to see updated?

**Comment by johnmichalak** [comment]
No response, so closing the issue for now.
