### ISSUE TITLE
Extend and embed mobile app

### ISSUE THREAD

**Issue by davecope1982** [MicrosoftDocs/dynamics-365-project-operations#94]
I have a couple of queries re the timesheet mobile app

1) Is it possible to extend the app to meet our specific processes?
2) Can the app be installed on laptops as well as mobiles?
3) Could we embed the app into F&O / CE so that it can be launched by users in line where they are working?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 89582dc3-c56c-e23d-2b31-40b8a6089b84
* Version Independent ID: 0949dae1-f0b5-9a90-afcb-a3dbd8026a1e
* Content: [Project timesheet mobile application](https://learn.microsoft.com/en-us/dynamics365/project-operations/prod-pma/project-timesheet)
* Content Source: [articles/prod-pma/project-timesheet.md](https://github.com/MicrosoftDocs/dynamics-365-project-operations/blob/main/articles/prod-pma/project-timesheet.md)
* Service: **dynamics-365-project-operations**
* Product: ****
* Technology: ****
* GitHub Login: @abruer
* Microsoft Alias: **andchoi**

**Comment by johnmichalak** [comment]
@davecope1982 Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.
